import type { Metadata } from 'next';
import { GeistSans } from 'geist/font';
import './globals.css';
import Header from '@/components/header';
import Tester from '@/components/tester';
import Footer from '@/components/footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${GeistSans.className} px-3 max-w-5xl mx-auto min-h-screen bg-gray-50`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
