import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} max-w-5xl mx-auto flex flex-col min-h-screen items-center justify-center animate-in fade-in slide-in-from-top-4 duration-1000 ease-in-out`}
      >
        {children}
      </body>
    </html>
  );
}
